### ISSUE TITLE
[Bug] Failed to run Server.exe: Entire<0> not found on map<0>, location

### ISSUE THREAD

**Issue by LinuxFO** [Sasabmeg/FOnline-BraveNewWorld#76]
Server log:
```
[0000:02:10:481] Load location proto<460:Sierra Caves Test>
[0000:02:10:481] Load map proto<700:template_cave_test>
[0000:02:10:533] MapManager::LoadLocationProto - Entire<0> not found on map<0>, location<Sierra Caves Test>.
[0000:02:10:533] Load location proto<460> fail.
```

Steps to reproduce:
1. Clone repository `git clone https://github.com/Sasabmeg/FOnline-BraveNewWorld.git`
2. Run `FOnline-BraveNewWorld/PReloaded/Server/Server.exe`

I guess it is related to the entry from `FOnline-BraveNewWorld/PReloaded/Server/maps/Locations.cfg`. No idea how to solve the issue, probably the map file named template_cave_test  misses an entity which is required.

```
[Area 460]
name=Sierra Caves Test
size=6
visible=1
auto_garbage=0
geck_visible=0
map_0=template_cave_test 700
entrance=1
```

**Comment by Sasabmeg** [comment]
Hi, yes, I was using that to test and didn't push some changes to repo I guess.

I have removed the test map and replaced the actual map that will be used for entry. Feature is still not finished, but it should work now.

In such cases, to shortcut such bugs/mistakes, you can either add an Entire with value 0 (first map that is part of a location must have this value, unless some other value given specifically, else engine will not know where to place the player when they enter the map from world map travel) or you can just delete the location itself, in this case was just a test.

Also do note that since I mostly use this repo alone, I sometimes shortcut or forget to push latest changes.

You can use the discord link given in main page for help as well, also there is an older version upload link in case current version doesn't work.

**Comment by LinuxFO** [comment]
Thanks.

Can you also say how to add or remove the location? I remember that deleting whole section `[Area 460]` did not help. Is there additional place?

**Comment by Sasabmeg** [comment]
Yes, pls use the world editor tool, in tools folder to make most changes that the world editor can. 

There you just delete the location either in location editor or select it from world map if you can find it there.

For such questions discord is better, try it out.

**Comment by LinuxFO** [comment]
Okay, I understand. I had an Discord account few year ago so I will find it and join. Thank you.
